-- Dong bo cot office_license (Key Office) cua KK_ThietBi theo file Office_license280926.csv (quet ngay 24/09/2026).
-- Cung noi dung voi file Import_KeyOffice_280926.xlsx: Licensed va Notification (da cai key, theo xac nhan 28/09
-- tinh la da kich hoat) trong CSV -> 'Co ban quyen'; khong co trong danh sach -> 'Chua co ban quyen'.
-- Pham vi: May tinh/Laptop chua xoa mem, co hostname. Thay doi 861 dong (101 -> Co, 760 -> Chua co);
-- cac dong da dung nhan chuan thi khong dung toi.
-- An toan: chi cap nhat dong con giu dung gia tri cu lay tu DB luc soan (28/09/2026) -> dong ai do vua sua tay se duoc bo qua,
-- chay lai lan hai se cap nhat 0 dong. Rollback: kk-key-office-license-20260928-rollback.sql
-- Chay bang sqlcmd phai them -f 65001 (file co tieng Viet).

SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRAN;

DECLARE @doi TABLE (id_thiet_bi INT PRIMARY KEY, gia_tri_cu NVARCHAR(255) NULL, gia_tri_moi NVARCHAR(255) NOT NULL);
INSERT INTO @doi (id_thiet_bi, gia_tri_cu, gia_tri_moi) VALUES
(3, N'Không có bản quyền', N'Chưa có bản quyền') /* ZP-IT003 */,
(4, N'Chưa có', N'Chưa có bản quyền') /* ZP-IT001 */,
(5, N'Chưa có', N'Chưa có bản quyền') /* ZP-IT004 */,
(6, N'Chưa có', N'Chưa có bản quyền') /* ZP-IT005 */,
(10, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT021 */,
(11, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT020 */,
(12, N'Chưa có', N'Chưa có bản quyền') /* ZP-CT005 */,
(13, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT031 */,
(14, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT028 */,
(15, NULL, N'Chưa có bản quyền') /* ZP-AC007 */,
(16, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA008 */,
(17, N'Chưa có', N'Chưa có bản quyền') /* ZP-QC008 */,
(18, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA010 */,
(19, N'Chưa có', N'Chưa có bản quyền') /* ZP-AC005 */,
(20, N'Chưa có', N'Chưa có bản quyền') /* ZP-AC002 */,
(21, N'Chưa có', N'Chưa có bản quyền') /* ZP-AC003 */,
(22, N'Chưa có', N'Chưa có bản quyền') /* ZP-AC004 */,
(23, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA014 */,
(24, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA004 */,
(25, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN008 */,
(26, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN016 */,
(27, NULL, N'Chưa có bản quyền') /* ZP-PUR017 */,
(28, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN004 */,
(30, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN015 */,
(31, NULL, N'Chưa có bản quyền') /* ZP-PUR004 */,
(32, NULL, N'Chưa có bản quyền') /* ZP-PUR001 */,
(34, N'Chưa có', N'Chưa có bản quyền') /* ZP-PUR007 */,
(35, NULL, N'Chưa có bản quyền') /* ZP-PUR014 */,
(36, NULL, N'Chưa có bản quyền') /* ZP-PUR016 */,
(37, NULL, N'Chưa có bản quyền') /* ZP-SHD004 */,
(38, NULL, N'Chưa có bản quyền') /* ZP-SHD005 */,
(39, N'Chưa có', N'Chưa có bản quyền') /* ZP-SHD009 */,
(40, NULL, N'Chưa có bản quyền') /* ZP-SHD007 */,
(41, NULL, N'Chưa có bản quyền') /* ZP-SHD008 */,
(42, NULL, N'Chưa có bản quyền') /* ZP-SHD006 */,
(43, NULL, N'Chưa có bản quyền') /* ZP-SHD001 */,
(44, NULL, N'Chưa có bản quyền') /* ZP-PUR011 */,
(45, N'Chưa có', N'Chưa có bản quyền') /* ZP-PUR012 */,
(46, N'Chưa có', N'Chưa có bản quyền') /* ZP-MD003 */,
(47, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN023 */,
(48, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD008 */,
(49, N'Chưa có', N'Chưa có bản quyền') /* ZP-MD008 */,
(50, N'Chưa có', N'Chưa có bản quyền') /* ZP-MD006 */,
(51, N'Có (Chưa rõ phiên bản)', N'Chưa có bản quyền') /* ZP-FN018 */,
(52, N'Chưa có', N'Chưa có bản quyền') /* ZP-MD007 */,
(53, N'Chưa có', N'Chưa có bản quyền') /* ZP-MD001 */,
(54, N'Chưa có', N'Chưa có bản quyền') /* ZP-EG002 */,
(55, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD001 */,
(56, N'Chưa có', N'Chưa có bản quyền') /* ZP-EG001 */,
(57, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD006 */,
(58, N'Chưa có', N'Chưa có bản quyền') /* ZP-MD002 */,
(59, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA013 */,
(60, N'Chưa có', N'Chưa có bản quyền') /* ZP-MD004 */,
(61, N'Chưa có', N'Chưa có bản quyền') /* V01 */,
(62, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN010 */,
(63, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD005 */,
(64, N'Chưa có', N'Chưa có bản quyền') /* V2 */,
(65, N'Chưa có', N'Chưa có bản quyền') /* V3 */,
(66, N'Chưa có', N'Chưa có bản quyền') /* V4 */,
(67, N'Chưa có', N'Chưa có bản quyền') /* V5 */,
(68, N'Chưa có', N'Chưa có bản quyền') /* V6 */,
(69, N'Chưa có', N'Chưa có bản quyền') /* V7 */,
(70, N'Chưa có', N'Chưa có bản quyền') /* V8 */,
(71, N'Chưa có', N'Chưa có bản quyền') /* V9 */,
(72, N'Chưa có', N'Chưa có bản quyền') /* V10 */,
(73, N'Chưa có', N'Chưa có bản quyền') /* V11 */,
(74, N'Chưa có', N'Chưa có bản quyền') /* V12 */,
(75, N'Chưa có', N'Chưa có bản quyền') /* V13 */,
(76, N'Chưa có', N'Chưa có bản quyền') /* V14 */,
(77, N'Chưa có', N'Chưa có bản quyền') /* V15 */,
(78, N'Chưa có', N'Chưa có bản quyền') /* V16 */,
(79, N'Chưa có', N'Chưa có bản quyền') /* V17 */,
(80, N'Chưa có', N'Chưa có bản quyền') /* V18 */,
(81, N'Chưa có', N'Chưa có bản quyền') /* V19 */,
(82, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW001 */,
(83, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW010 */,
(84, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW011 */,
(85, N'Chưa có', N'Chưa có bản quyền') /* ZP-PUR013 */,
(86, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW004 */,
(87, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW003 */,
(88, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW008 */,
(89, N'Chưa có', N'Chưa có bản quyền') /* ZP-QC002 */,
(90, N'Chưa có', N'Chưa có bản quyền') /* ZP-QC006 */,
(92, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR001 */,
(93, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR004 */,
(94, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR009 */,
(95, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR005 */,
(96, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR002 */,
(97, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR003 */,
(98, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR007 */,
(99, N'Chưa có', N'Chưa có bản quyền') /* ZP-IEV002 */,
(100, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR015 */,
(101, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR010 */,
(102, NULL, N'Chưa có bản quyền') /* ZP-HR006 */,
(103, NULL, N'Chưa có bản quyền') /* ZP-IE003 */,
(104, N'Chưa có', N'Chưa có bản quyền') /* V20 */,
(105, N'Chưa có', N'Chưa có bản quyền') /* V21 */,
(106, N'Chưa có', N'Chưa có bản quyền') /* V22 */,
(107, N'Chưa có', N'Chưa có bản quyền') /* V23 */,
(108, N'Chưa có', N'Chưa có bản quyền') /* V24 */,
(109, N'Chưa có', N'Chưa có bản quyền') /* V25 */,
(110, N'Chưa có', N'Chưa có bản quyền') /* V26 */,
(112, NULL, N'Chưa có bản quyền') /* ZP-IE007 */,
(113, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW011 */,
(114, NULL, N'Chưa có bản quyền') /* ZP-IE012 */,
(115, N'Chưa có', N'Chưa có bản quyền') /* ZP-IE013 */,
(116, NULL, N'Chưa có bản quyền') /* ZP-IE010 */,
(117, NULL, N'Chưa có bản quyền') /* ZP-IE002 */,
(118, NULL, N'Chưa có bản quyền') /* ZP-IE005 */,
(119, N'Chưa có', N'Chưa có bản quyền') /* ZP-IE004 */,
(120, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW012 */,
(121, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT026 */,
(122, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT025 */,
(124, N'Chưa có', N'Chưa có bản quyền') /* ZP-CT033 */,
(125, N'Chưa có', N'Chưa có bản quyền') /* ZP-CT012 */,
(126, N'Chưa có', N'Chưa có bản quyền') /* ZP-CT010 */,
(127, N'Chưa có', N'Chưa có bản quyền') /* ZP-HT001 */,
(128, NULL, N'Chưa có bản quyền') /* ZP-AC008 */,
(129, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT027 */,
(130, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD003 */,
(131, N'Chưa có', N'Chưa có bản quyền') /* ZP-CT008 */,
(132, N'Chưa có', N'Chưa có bản quyền') /* ZP-CT013 */,
(133, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD009 */,
(134, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD012 */,
(135, NULL, N'Chưa có bản quyền') /* ZP-PMC009 */,
(137, NULL, N'Chưa có bản quyền') /* ZP-PMC002 */,
(138, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC019 */,
(139, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC018 */,
(140, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC012 */,
(141, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC005 */,
(142, NULL, N'Chưa có bản quyền') /* ZP-PMC008 */,
(143, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC010 */,
(144, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC007 */,
(145, NULL, N'Chưa có bản quyền') /* ZP-PMC013 */,
(146, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW023 */,
(147, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW025 */,
(148, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW005 */,
(149, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW006 */,
(150, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW012 */,
(151, NULL, N'Chưa có bản quyền') /* ZP-SW013 */,
(152, NULL, N'Chưa có bản quyền') /* ZP-SW004 */,
(153, NULL, N'Chưa có bản quyền') /* ZP-SW010 */,
(154, NULL, N'Chưa có bản quyền') /* ZP-SW009 */,
(155, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW024 */,
(158, N'Có (Chưa rõ phiên bản)', N'Chưa có bản quyền') /* CUT1 */,
(159, N'Có (Chưa rõ phiên bản)', N'Chưa có bản quyền') /* CUT2 */,
(160, N'Có (Chưa rõ phiên bản)', N'Chưa có bản quyền') /* CUT3 */,
(161, N'Có (Chưa rõ phiên bản)', N'Chưa có bản quyền') /* CUT4 */,
(162, N'Có (Chưa rõ phiên bản)', N'Chưa có bản quyền') /* CUT5 */,
(163, N'Chưa có', N'Chưa có bản quyền') /* ZP-IEV003 */,
(164, N'Chưa có', N'Chưa có bản quyền') /* VN-EG024 */,
(165, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT034 */,
(166, N'Chưa có', N'Chưa có bản quyền') /* VN-HR060 */,
(167, NULL, N'Chưa có bản quyền') /* ZP-CUT030 */,
(168, N'Chưa có', N'Chưa có bản quyền') /* VN-HR065 */,
(169, N'Chưa có', N'Chưa có bản quyền') /* VN-PD008 */,
(170, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN001 */,
(171, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN011 */,
(172, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN005 */,
(173, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN017 */,
(174, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN019 */,
(175, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN012 */,
(176, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA011 */,
(177, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA012 */,
(178, N'Chưa có', N'Chưa có bản quyền') /* VN-WK063 */,
(179, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA001 */,
(180, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA003 */,
(181, N'Chưa có', N'Chưa có bản quyền') /* VN-WK065 */,
(182, N'Chưa có', N'Chưa có bản quyền') /* VN-WK045 */,
(183, NULL, N'Chưa có bản quyền') /* ZP-FN014 */,
(184, N'Chưa có', N'Chưa có bản quyền') /* ZP-WH002 */,
(185, N'Office Professional Plus', N'Chưa có bản quyền') /* ZP-CT001 */,
(186, N'Chưa có', N'Chưa có bản quyền') /* VN-WK070 */,
(187, N'Chưa có', N'Chưa có bản quyền') /* ZP-QC007 */,
(188, N'Chưa có', N'Chưa có bản quyền') /* VN-WK068 */,
(189, NULL, N'Chưa có bản quyền') /* ZP-QC003 (HỎNG) */,
(190, NULL, N'Chưa có bản quyền') /* ZP-QC000 */,
(191, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK046 */,
(192, N'Chưa có', N'Chưa có bản quyền') /* VN-WK044 */,
(193, NULL, N'Chưa có bản quyền') /* ZP-WH009 */,
(194, N'Chưa có', N'Chưa có bản quyền') /* VN-WK062 */,
(195, NULL, N'Chưa có bản quyền') /* ZP-WH006 */,
(196, N'Chưa có', N'Chưa có bản quyền') /* VN-WK059 */,
(198, NULL, N'Chưa có bản quyền') /* ZP-WH007 */,
(199, NULL, N'Chưa có bản quyền') /* ZP-WH010 */,
(200, NULL, N'Chưa có bản quyền') /* ZP-WH001 */,
(201, N'Chưa có', N'Chưa có bản quyền') /* VN-WK071 */,
(202, N'Chưa có', N'Chưa có bản quyền') /* ZP-WH011 */,
(203, N'Chưa có', N'Chưa có bản quyền') /* VN-WK048 */,
(204, N'Chưa có', N'Chưa có bản quyền') /* ZP-WH014 */,
(205, N'Chưa có', N'Chưa có bản quyền') /* VN-WH047 */,
(206, NULL, N'Chưa có bản quyền') /* ZP-WH004 */,
(207, N'Chưa có', N'Chưa có bản quyền') /* ZP-WH015 */,
(208, NULL, N'Chưa có bản quyền') /* ZP-WH008 */,
(209, N'Chưa có', N'Chưa có bản quyền') /* VN-EG019 */,
(210, N'Chưa có', N'Chưa có bản quyền') /* ZP-GM002 */,
(212, N'Chưa có', N'Chưa có bản quyền') /* VN-HR071 */,
(213, N'Chưa có', N'Chưa có bản quyền') /* VN-EG029 */,
(215, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN022 */,
(216, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN021 */,
(217, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW019 */,
(218, N'Chưa có', N'Chưa có bản quyền') /* ZP-IE014 */,
(219, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC015 */,
(220, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW018 */,
(221, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC017 */,
(222, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW017 */,
(223, N'Chưa có', N'Chưa có bản quyền') /* ZP-WH013 */,
(224, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC016 */,
(225, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW016 */,
(226, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR017 */,
(227, N'Chưa có', N'Chưa có bản quyền') /* VN-HR070 */,
(228, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR011 */,
(229, N'Chưa có', N'Chưa có bản quyền') /* ZP-HR016 */,
(230, N'Chưa có', N'Chưa có bản quyền') /* VN-PW016 */,
(231, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC014 */,
(232, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW005 */,
(233, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW009 */,
(234, N'Chưa có', N'Chưa có bản quyền') /* ZP-QC010 */,
(235, N'Chưa có', N'Chưa có bản quyền') /* ZP-IE006 */,
(236, N'Chưa có', N'Chưa có bản quyền') /* ZP-QC009 */,
(237, N'Chưa có', N'Chưa có bản quyền') /* ZP-FN020 */,
(238, NULL, N'Chưa có bản quyền') /* ZP-HR012 */,
(239, NULL, N'Chưa có bản quyền') /* ZP-HR013 */,
(240, NULL, N'Chưa có bản quyền') /* ZP-IE001 */,
(241, NULL, N'Chưa có bản quyền') /* ZP-IE008 */,
(242, N'Chưa có', N'Chưa có bản quyền') /* ZP-GM003 */,
(243, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC011 */,
(244, NULL, N'Chưa có bản quyền') /* ZP-HR018 */,
(245, N'Chưa có', N'Chưa có bản quyền') /* ZP-QA015 */,
(246, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT032 */,
(247, NULL, N'Chưa có bản quyền') /* ZP-CUT035 */,
(248, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT036 */,
(249, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW021 */,
(250, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW022 */,
(251, N'Có (Chưa rõ phiên bản)', N'Chưa có bản quyền') /* CUT6 */,
(254, NULL, N'Chưa có bản quyền') /* ZP-QC003 */,
(256, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW023 */,
(257, N'Chưa có', N'Chưa có bản quyền') /* ZP-EG003 */,
(258, N'Chưa có', N'Chưa có bản quyền') /* ZP-EG005 */,
(259, NULL, N'Chưa có bản quyền') /* ZP-SEW024 */,
(260, NULL, N'Chưa có bản quyền') /* ZP-SEW025 */,
(272, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW013 */,
(282, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW016 */,
(295, N'Chưa có', N'Chưa có bản quyền') /* ZP-CUT023 */,
(297, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW015 */,
(300, NULL, N'Chưa có bản quyền') /* ZP-PUR008 */,
(308, N'Chưa có', N'Chưa có bản quyền') /* ZP-CT004 */,
(316, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC006 */,
(327, N'Chưa có', N'Chưa có bản quyền') /* ZP-PMC020 */,
(328, N'Chưa có', N'Chưa có bản quyền') /* YNZP-PD03 */,
(329, N'Chưa có', N'Chưa có bản quyền') /* ZP-SD007 */,
(330, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW002 */,
(331, N'Chưa có', N'Chưa có bản quyền') /* GDZP-GM17 */,
(332, N'Chưa có', N'Chưa có bản quyền') /* ZP-SW020 */,
(333, N'Chưa có', N'Chưa có bản quyền') /* VN-EG023 */,
(335, N'Chưa có', N'Chưa có bản quyền') /* VN-HR079 */,
(336, N'Chưa có', N'Chưa có bản quyền') /* VN-HR080 */,
(337, N'Chưa có', N'Chưa có bản quyền') /* ZP-SEW019 */,
(340, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK057 */,
(342, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IT086 */,
(343, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DCV002 */,
(344, N'Không có bản quyền', N'Có bản quyền') /* VN-PUR030 */,
(345, N'Không xác định', N'Chưa có bản quyền') /* VN-ITV015 */,
(354, N'Có bản quyền', N'Chưa có bản quyền') /* VN-RD002 */,
(357, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IT023 */,
(360, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IT018 */,
(362, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR001 */,
(363, N'Không có bản quyền', N'Có bản quyền') /* VN-HR043 */,
(365, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR052 */,
(367, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR059 */,
(368, N'Không có bản quyền', N'Có bản quyền') /* VN-HR018 */,
(370, N'Không có bản quyền', N'Có bản quyền') /* VN-LD047 */,
(372, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD051 */,
(374, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD038 */,
(391, N'Chưa có bản quyền', N'Có bản quyền') /* VN-LD009 */,
(392, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD048 */,
(393, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD039 */,
(395, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD053 */,
(397, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD059 */,
(400, N'Không có bản quyền', N'Có bản quyền') /* VN-PMC057 */,
(403, N'Có bản quyền', N'Chưa có bản quyền') /* VN-CV005 */,
(404, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DF027 */,
(405, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-DF028 */,
(406, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DF010 */,
(407, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-DF026 */,
(410, N'Không có bản quyền', N'Có bản quyền') /* VN-DF024 */,
(413, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH021 */,
(414, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH013 */,
(415, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH038 */,
(416, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH005 */,
(419, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-DH031 */,
(420, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH032 */,
(421, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH024 */,
(422, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH026 */,
(423, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH011 */,
(424, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-EG009 */,
(426, N'Có bản quyền', N'Chưa có bản quyền') /* VN-EG012 */,
(427, N'Không xác định', N'Chưa có bản quyền') /* VN-MAXHUB-360 */,
(428, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA014 */,
(430, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA044 */,
(431, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA007 */,
(432, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA004 */,
(434, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA042 */,
(436, N'Không có bản quyền', N'Có bản quyền') /* VN-QA046 */,
(437, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA033 */,
(439, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA031 */,
(440, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA051 */,
(441, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC040 */,
(448, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QC069 */,
(451, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC063 */,
(452, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC039 */,
(455, N'Không xác định', N'Chưa có bản quyền') /* VN-QC080 */,
(456, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC14 */,
(462, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QC084 */,
(468, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC067 */,
(470, N'Không xác định', N'Chưa có bản quyền') /* VN-QC034 */,
(472, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC073 */,
(477, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD101 */,
(479, N'Không có bản quyền', N'Có bản quyền') /* VN-SHD007 */,
(480, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS001 */,
(481, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS049 */,
(482, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS064 */,
(483, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS065 */,
(484, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS037 */,
(487, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS057 */,
(488, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SS043 */,
(489, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS075 */,
(490, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS025 */,
(494, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SS080 */,
(495, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS053 */,
(496, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS076 */,
(497, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS056 */,
(498, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS034 */,
(499, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS059 */,
(503, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS061 */,
(504, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS033 */,
(506, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA026 */,
(507, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA027 */,
(508, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA019 */,
(511, N'Không có bản quyền', N'Có bản quyền') /* VN-WA006 */,
(512, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA046 */,
(514, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA045 */,
(515, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA044 */,
(516, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA043 */,
(518, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA024 */,
(519, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WD013 */,
(520, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WD009 */,
(522, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WD012 */,
(523, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WD002 */,
(524, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WD008 */,
(525, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WD005 */,
(526, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH050 */,
(527, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH010 */,
(528, N'Chưa có bản quyền', N'Có bản quyền') /* VN-WH012 */,
(531, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH036 */,
(532, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH037 */,
(536, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH040 */,
(539, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK069 */,
(541, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK037 */,
(545, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK041 */,
(546, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK021 */,
(550, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK054 */,
(552, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK033 */,
(555, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK004 */,
(558, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WV018 */,
(559, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WV019 */,
(562, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WV028 */,
(570, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PW011 */,
(579, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB037 */,
(581, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB006 */,
(583, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB048 */,
(584, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTB045 */,
(586, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB043 */,
(587, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB042 */,
(588, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB025 */,
(589, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB029 */,
(590, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTB030 */,
(591, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB023 */,
(592, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB031 */,
(593, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB024 */,
(595, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB035 */,
(597, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PT050 */,
(598, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PT01 */,
(600, N'Không xác định', N'Chưa có bản quyền') /* VN-PT015 */,
(602, N'Không xác định', N'Chưa có bản quyền') /* TE-236S */,
(603, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PT012 */,
(606, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB046 */,
(607, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DF004 */,
(608, N'Không có bản quyền', N'Có bản quyền') /* VN-WV014 */,
(609, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC051 */,
(610, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC053 */,
(611, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC045 */,
(613, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC050 */,
(614, N'Không có bản quyền', N'Có bản quyền') /* VN-WA013 */,
(615, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD001 */,
(616, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SD066 */,
(618, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK001 */,
(626, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD111 */,
(628, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD121 */,
(630, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-RD009 */,
(631, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-IT001 */,
(633, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IT011 */,
(637, N'Chưa có bản quyền', N'Có bản quyền') /* VN-AC027 */,
(641, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR058 */,
(645, N'Có bản quyền', N'Chưa có bản quyền') /* VN-HR078 */,
(646, N'Không có bản quyền', N'Có bản quyền') /* VN-HR017 */,
(647, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR055 */,
(649, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR037 */,
(650, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR045 */,
(652, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD024 */,
(656, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD043 */,
(658, N'Không có bản quyền', N'Có bản quyền') /* VN-PMC048 */,
(660, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC041 */,
(663, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC010 */,
(668, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC003 */,
(671, N'Không xác định', N'Có bản quyền') /* VN-PMC062 */,
(673, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC052 */,
(674, N'Không xác định', N'Chưa có bản quyền') /* VN-PMC066 */,
(676, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PMC067 */,
(677, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC030 */,
(679, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC036 */,
(680, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC027 */,
(681, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC049 */,
(683, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC022 */,
(686, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC019 */,
(687, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC037 */,
(689, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC013 */,
(690, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PMC069 */,
(691, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC058 */,
(693, N'Có bản quyền', N'Chưa có bản quyền') /* VN-CV003 */,
(696, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DF025 */,
(705, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH010 */,
(707, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH002 */,
(708, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DH034 */,
(710, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IMD001 */,
(713, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IMD008 */,
(714, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-IMD005 */,
(715, N'Có bản quyền', N'Chưa có bản quyền') /* VN-EG026 */,
(717, N'Không xác định', N'Chưa có bản quyền') /* VN-EG022 */,
(719, N'Không xác định', N'Có bản quyền') /* VN-GM029 */,
(721, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR032 */,
(722, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR018 */,
(723, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR019 */,
(724, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR033 */,
(727, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR039 */,
(729, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA027 */,
(730, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR027 */,
(732, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA006 */,
(738, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA048 */,
(739, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA037 */,
(740, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA041 */,
(741, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA056 */,
(742, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA059 */,
(743, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA099 */,
(745, N'Chưa có bản quyền', N'Có bản quyền') /* VN-QC04 */,
(746, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC032 */,
(751, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC075 */,
(752, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QC074 */,
(755, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD141 */,
(756, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD113 */,
(758, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD114 */,
(759, N'Không có bản quyền', N'Có bản quyền') /* VN-SD089 */,
(760, N'Không xác định', N'Có bản quyền') /* VN-SD134 */,
(761, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD057 */,
(762, N'Không có bản quyền', N'Có bản quyền') /* VN-SD116 */,
(763, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD128 */,
(764, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD146 */,
(767, N'Không xác định', N'Có bản quyền') /* VN-SD015 */,
(768, N'Không có bản quyền', N'Có bản quyền') /* VN-SD158 */,
(771, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD138 */,
(772, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD131 */,
(773, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD092 */,
(775, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD148 */,
(776, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD091 */,
(777, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SD125 */,
(779, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SD126 */,
(781, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SD021 */,
(783, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD151 */,
(785, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD076 */,
(786, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD031 */,
(788, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD020 */,
(791, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD109 */,
(793, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD000 */,
(794, N'Không có bản quyền', N'Có bản quyền') /* VN-SD139 */,
(795, N'Không có bản quyền', N'Có bản quyền') /* VN-SD006 */,
(796, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD122 */,
(798, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD135 */,
(799, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD153 */,
(802, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD129 */,
(803, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SD036 */,
(805, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD130 */,
(808, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD072 */,
(809, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD144 */,
(814, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD142 */,
(815, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD157 */,
(816, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD145 */,
(818, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD080 */,
(825, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SHD028 */,
(826, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SHD015 */,
(827, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SHD036 */,
(829, N'Không có bản quyền', N'Có bản quyền') /* VN-SHD035 */,
(830, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SHD041 */,
(831, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SHD042 */,
(832, N'Không có bản quyền', N'Có bản quyền') /* VN-SS011 */,
(833, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SS054 */,
(836, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS058 */,
(838, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SS048 */,
(840, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS081 */,
(841, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS060 */,
(843, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SS030-1 */,
(844, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA017 */,
(845, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA018 */,
(846, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA021 */,
(847, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA022 */,
(851, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WA053 */,
(852, N'Không có bản quyền', N'Có bản quyền') /* VN-WD004 */,
(854, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH005 */,
(855, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH052 */,
(858, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK042 */,
(859, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK005 */,
(860, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK051 */,
(861, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK052 */,
(862, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK035 */,
(865, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV020 */,
(867, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WV017 */,
(868, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WV012 */,
(869, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WV025 */,
(871, N'Có bản quyền', N'Chưa có bản quyền') /* VN-RDD001 */,
(872, N'Không có bản quyền', N'Có bản quyền') /* VN-WV030 */,
(873, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WV007 */,
(875, N'Có bản quyền', N'Chưa có bản quyền') /* VN-YDF005 */,
(877, N'Không xác định', N'Chưa có bản quyền') /* VN-YDF002 */,
(879, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB019 */,
(883, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTB016 */,
(884, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTB049 */,
(885, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTB060 */,
(886, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB041 */,
(888, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB012 */,
(889, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB026 */,
(890, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTB022 */,
(891, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB027 */,
(893, N'Không xác định', N'Chưa có bản quyền') /* VN-LTB028 */,
(894, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB052 */,
(896, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB047 */,
(897, N'Chưa có bản quyền', N'Có bản quyền') /* VN-LTBD004 */,
(898, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB004 */,
(900, N'Không có bản quyền', N'Có bản quyền') /* VN-PT013 */,
(901, N'Chưa có bản quyền', N'Có bản quyền') /* VN-ITV026 */,
(903, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-ITV020 */,
(904, N'Chưa có bản quyền', N'Có bản quyền') /* VN-ITV010 */,
(905, N'Chưa có bản quyền', N'Có bản quyền') /* VN-ITV014 */,
(907, N'Có bản quyền', N'Chưa có bản quyền') /* VN-TL002 */,
(908, N'Có bản quyền', N'Chưa có bản quyền') /* VN-TL003 */,
(909, N'Không xác định', N'Chưa có bản quyền') /* VN-TL001 */,
(910, N'Chưa có bản quyền', N'Có bản quyền') /* VN-HR025 */,
(912, N'Không xác định', N'Có bản quyền') /* VN-AC017 */,
(915, N'Chưa có bản quyền', N'Có bản quyền') /* VN-AC033 */,
(917, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LD008 */,
(919, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC043 */,
(921, N'Không xác định', N'Chưa có bản quyền') /* VN-DH025 */,
(922, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-EG017 */,
(923, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IE020 */,
(926, N'Không có bản quyền', N'Có bản quyền') /* VN-PMC021 */,
(927, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD104 */,
(932, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SHD032 */,
(933, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SS063 */,
(934, N'Không xác định', N'Chưa có bản quyền') /* VN-SS024 */,
(935, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA020 */,
(936, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH056 */,
(937, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK022 */,
(939, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTBD005-1 */,
(940, N'Có bản quyền', N'Chưa có bản quyền') /* VN-EG016 */,
(941, N'Có bản quyền', N'Chưa có bản quyền') /* VN-GL011 */,
(966, N'Không có bản quyền', N'Có bản quyền') /* VN-AC018 */,
(967, N'Không có bản quyền', N'Có bản quyền') /* VN-AC021 */,
(968, N'Không xác định', N'Chưa có bản quyền') /* VN-HR050 */,
(969, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD052 */,
(971, N'Không có bản quyền', N'Có bản quyền') /* VN-PMC006 */,
(972, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC054 */,
(973, N'Không xác định', N'Chưa có bản quyền') /* VN-WH064 */,
(974, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-EG020 */,
(975, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR005 */,
(976, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA038 */,
(977, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA039 */,
(978, N'Có bản quyền', N'Chưa có bản quyền') /* VN-QA045 */,
(981, N'Không có bản quyền', N'Có bản quyền') /* VN-SD090 */,
(982, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD127 */,
(983, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD123 */,
(984, N'Có bản quyền', N'Chưa có bản quyền') /* VN-SD140 */,
(986, N'Không xác định', N'Có bản quyền') /* VN-SD154 */,
(987, N'Không có bản quyền', N'Có bản quyền') /* VN-SD150 */,
(989, N'Không xác định', N'Chưa có bản quyền') /* VN-SHD034 */,
(990, N'Không xác định', N'Chưa có bản quyền') /* VN-SS062 */,
(991, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK013 */,
(992, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK053 */,
(993, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK039 */,
(994, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB034 */,
(995, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-IT091 */,
(999, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PUR035 */,
(1001, N'Có bản quyền', N'Chưa có bản quyền') /* VN-HR012 */,
(1003, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC055 */,
(1004, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PMC064 */,
(1005, N'Chưa có bản quyền', N'Có bản quyền') /* VN-PMC060 */,
(1008, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DF002 */,
(1009, N'Có bản quyền', N'Chưa có bản quyền') /* VN-DF019 */,
(1010, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PUR040 */,
(1015, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD050 */,
(1017, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SD095 */,
(1018, N'Chưa có bản quyền', N'Có bản quyền') /* VN-SD051 */,
(1020, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD120 */,
(1023, N'Không có bản quyền', N'Có bản quyền') /* VN-SD023 */,
(1040, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA037 */,
(1041, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA040 */,
(1042, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA041 */,
(1043, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA042 */,
(1044, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA047 */,
(1046, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WA052 */,
(1051, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WH039 */,
(1056, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB053 */,
(1057, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB054 */,
(1062, N'Có bản quyền', N'Chưa có bản quyền') /* VN-PT009 */,
(1063, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-ITV018 */,
(1064, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-HR076 */,
(1065, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PMC063 */,
(1066, N'Không có bản quyền', N'Có bản quyền') /* VN-DH037 */,
(1069, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD137 */,
(1070, N'Không có bản quyền', N'Có bản quyền') /* VN-WV039 */,
(1071, N'Không có bản quyền', N'Có bản quyền') /* VN-PMC047 */,
(1072, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PUR031 */,
(1073, N'Không có bản quyền', N'Có bản quyền') /* VN-PT006 */,
(1078, N'Không có bản quyền', N'Có bản quyền') /* VN-PUR034 */,
(1088, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WA030 */,
(1089, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK061 */,
(1090, N'Có bản quyền', N'Chưa có bản quyền') /* VN-IE012 */,
(1091, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTBD003 */,
(1093, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LD016 */,
(1106, N'Không có bản quyền', N'Có bản quyền') /* VN-LD018 */,
(1108, N'Không có bản quyền', N'Có bản quyền') /* VN-LD011 */,
(1116, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PMC004 */,
(1168, N'Không có bản quyền', N'Chưa có bản quyền') /* ZP-SW018 */,
(1185, N'Có bản quyền', N'Chưa có bản quyền') /* VN-GL017 */,
(1193, N'Có bản quyền', N'Chưa có bản quyền') /* VN-GL006 */,
(1205, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QC072 */,
(1221, N'Không xác định', N'Chưa có bản quyền') /* VN-WV034 */,
(1230, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-LTBD002 */,
(1236, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PUR017 */,
(1248, N'Không có bản quyền', N'Có bản quyền') /* VN-QC081 */,
(1254, N'Không xác định', N'Chưa có bản quyền') /* VN-WK058 */,
(1327, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LTB021 */,
(1350, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV006 */,
(1352, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-GL016 */,
(1353, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV027 */,
(1401, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV013 */,
(1404, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK060 */,
(1417, N'Có bản quyền', N'Chưa có bản quyền') /* VN-GL014 */,
(1427, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV009 */,
(1468, N'Không có bản quyền', N'Có bản quyền') /* VN-SS072 */,
(1549, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH035 */,
(1559, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH049 */,
(1566, N'Không có bản quyền', N'Có bản quyền') /* VN-WH001 */,
(1567, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-HR005 */,
(1568, N'Không có bản quyền', N'Có bản quyền') /* VN-HR053 */,
(1576, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-RD005 */,
(1593, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH041 */,
(1629, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD029 */,
(1633, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH063 */,
(1637, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH043 */,
(1639, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SS020 */,
(1647, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV021 */,
(1649, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH048 */,
(1652, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-RD006 */,
(1661, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WA048 */,
(1675, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WA050 */,
(1688, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA055 */,
(1699, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH058 */,
(1705, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA052 */,
(1714, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-ITV009 */,
(1716, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH060 */,
(1725, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK055 */,
(1733, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PT016 */,
(1735, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD118 */,
(1738, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SS026 */,
(1751, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-PQC003 */,
(1764, N'Không có bản quyền', N'Có bản quyền') /* VN-SS071 */,
(1773, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WK049 */,
(1777, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV033 */,
(1784, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH053 */,
(1790, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WK031 */,
(1793, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH057 */,
(1821, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV001 */,
(1825, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WV032 */,
(1861, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-ITV011 */,
(1862, N'Không xác định', N'Chưa có bản quyền') /* VN-WH019 */,
(1873, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH044 */,
(1878, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SHD020 */,
(1880, N'Có bản quyền', N'Chưa có bản quyền') /* VN-GL003 */,
(1881, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-GL025 */,
(1883, N'Không có bản quyền', N'Có bản quyền') /* VN-GL020 */,
(1887, NULL, N'Chưa có bản quyền') /* VN-AC006 */,
(1893, NULL, N'Chưa có bản quyền') /* VN-QA058 */,
(1900, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA013 */,
(1906, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA043 */,
(1909, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-QA015 */,
(1912, N'Không có bản quyền', N'Có bản quyền') /* VN-ITV008 */,
(1914, N'Không có bản quyền', N'Chưa có bản quyền') /* CS-SUPERVIS-NEW */,
(1916, N'Không xác định', N'Chưa có bản quyền') /* DLV-DF */,
(1918, N'Không xác định', N'Chưa có bản quyền') /* SM-4 */,
(1919, N'Không có bản quyền', N'Chưa có bản quyền') /* YDF002 */,
(1920, N'Không xác định', N'Chưa có bản quyền') /* SM-3 */,
(1921, N'Không xác định', N'Chưa có bản quyền') /* DH02 */,
(1922, N'Không xác định', N'Chưa có bản quyền') /* SM-2 */,
(1923, N'Không có bản quyền', N'Chưa có bản quyền') /* YDF001 */,
(1924, N'Có bản quyền', N'Chưa có bản quyền') /* VN-LD031 */,
(1926, N'Có bản quyền', N'Chưa có bản quyền') /* VN-GL015 */,
(1942, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-ITV017 */,
(1943, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-GL012 */,
(1947, N'Không có bản quyền', N'Có bản quyền') /* VN-GL010 */,
(1951, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-WH045 */,
(1952, N'Không có bản quyền', N'Chưa có bản quyền') /* VN-SD030 */,
(1963, NULL, N'Chưa có bản quyền') /* TRS */,
(1964, NULL, N'Chưa có bản quyền') /* DAPG */,
(1966, NULL, N'Chưa có bản quyền') /* VN-WK020 */,
(1970, NULL, N'Chưa có bản quyền') /* VN-WK011 */,
(1981, NULL, N'Chưa có bản quyền') /* VN-GL023 */,
(1986, NULL, N'Chưa có bản quyền') /* VN-GL024 */,
(1991, NULL, N'Chưa có bản quyền') /* VN-QC082 */,
(2080, NULL, N'Chưa có bản quyền') /* VN-ITV021 */,
(2081, NULL, N'Chưa có bản quyền') /* VN-ITV013 */,
(2083, NULL, N'Chưa có bản quyền') /* SM-1 */,
(2084, NULL, N'Chưa có bản quyền') /* SM-1. */,
(2086, NULL, N'Chưa có bản quyền') /* VN-LD021 */,
(2107, NULL, N'Chưa có bản quyền') /* VN-QA010 */,
(2114, NULL, N'Chưa có bản quyền') /* YDF003 */,
(2118, NULL, N'Chưa có bản quyền') /* VN-DH035 */,
(2119, NULL, N'Có bản quyền') /* VN-ITV001 */,
(2120, NULL, N'Chưa có bản quyền') /* VN-ITV002 */,
(2121, NULL, N'Chưa có bản quyền') /* VN-ITV004 */,
(2122, NULL, N'Chưa có bản quyền') /* VN-ITV006 */,
(2123, NULL, N'Chưa có bản quyền') /* VN-ITV007 */,
(2124, NULL, N'Chưa có bản quyền') /* VN-ITV012 */,
(2125, NULL, N'Chưa có bản quyền') /* VN-ITV016 */,
(2126, NULL, N'Chưa có bản quyền') /* VN-ITV019 */,
(2127, NULL, N'Chưa có bản quyền') /* VN-ITV022 */,
(2128, NULL, N'Chưa có bản quyền') /* VN-ITV023 */,
(2129, NULL, N'Chưa có bản quyền') /* VN-ITV024 */,
(2130, NULL, N'Có bản quyền') /* VN-ITV025 */,
(2131, NULL, N'Chưa có bản quyền') /* VN-ITV027 */,
(2132, NULL, N'Chưa có bản quyền') /* VN-ITV028 */,
(2133, NULL, N'Chưa có bản quyền') /* VN-ITV029 */,
(2134, NULL, N'Chưa có bản quyền') /* VN-ITV030 */,
(2135, NULL, N'Chưa có bản quyền') /* VN-DH004 */,
(2141, NULL, N'Chưa có bản quyền') /* VN-DH041 */,
(2142, NULL, N'Chưa có bản quyền') /* VN-LTB065 */,
(2147, NULL, N'Chưa có bản quyền') /* DF-COPOWER 2 */,
(2148, NULL, N'Chưa có bản quyền') /* DF-COPOWER 1 */,
(2151, NULL, N'Chưa có bản quyền') /* LD-COPOWER 2 */,
(2154, NULL, N'Chưa có bản quyền') /* VN-WD016 */,
(2158, NULL, N'Chưa có bản quyền') /* VN-WD019 */,
(2161, NULL, N'Chưa có bản quyền') /* VN-GM030 */,
(2162, NULL, N'Chưa có bản quyền') /* VN-SD132 */,
(2163, NULL, N'Chưa có bản quyền') /* VN-PUR021 */,
(2164, NULL, N'Chưa có bản quyền') /* VN-SD124 */,
(2166, NULL, N'Chưa có bản quyền') /* VN-HR042 */,
(2168, NULL, N'Chưa có bản quyền') /* VN-HR036 */,
(2169, NULL, N'Chưa có bản quyền') /* VN-HR077 */,
(2170, NULL, N'Chưa có bản quyền') /* VN-QA057 */,
(2173, NULL, N'Chưa có bản quyền') /* VN-SD059 */,
(2176, NULL, N'Chưa có bản quyền') /* VN-WH033 */,
(2177, NULL, N'Chưa có bản quyền') /* VN-WH031 */,
(2178, NULL, N'Chưa có bản quyền') /* VN-IT088 */,
(2179, NULL, N'Chưa có bản quyền') /* VN-IT1001 */,
(2180, NULL, N'Chưa có bản quyền') /* VN-IT090 */,
(2185, NULL, N'Chưa có bản quyền') /* VN-IE009 */,
(2187, NULL, N'Chưa có bản quyền') /* VN-HR099 */,
(2188, NULL, N'Chưa có bản quyền') /* VN-SHD333 */,
(2190, NULL, N'Chưa có bản quyền') /* VN-SHD010 */,
(2191, NULL, N'Chưa có bản quyền') /* VN-HR073 */,
(2192, NULL, N'Chưa có bản quyền') /* VN-GM000 */,
(2193, NULL, N'Chưa có bản quyền') /* VN-EG027 */,
(2198, NULL, N'Có bản quyền') /* VN-TL005 */,
(2199, NULL, N'Chưa có bản quyền') /* VN-LD060 */,
(2200, NULL, N'Có bản quyền') /* VN-DF013 */,
(2205, NULL, N'Chưa có bản quyền') /* VN-QC087 */,
(2207, NULL, N'Chưa có bản quyền') /* VN-LD061 */,
(2210, NULL, N'Chưa có bản quyền') /* LD-COPOWER */,
(2213, NULL, N'Chưa có bản quyền') /* DOSORAMA */,
(2215, NULL, N'Chưa có bản quyền') /* DOSORAMA 2 */,
(2217, NULL, N'Chưa có bản quyền') /* DOSORAMA 3 */,
(2219, NULL, N'Chưa có bản quyền') /* VN-WA039 */,
(2221, NULL, N'Chưa có bản quyền') /* VN-WA038 */,
(2223, NULL, N'Chưa có bản quyền') /* VN-WA025 */,
(2225, NULL, N'Chưa có bản quyền') /* VN-SD012 */,
(2228, NULL, N'Chưa có bản quyền') /* VN-SS046 */,
(2231, NULL, N'Chưa có bản quyền') /* VN-SHD039 */,
(2234, NULL, N'Chưa có bản quyền') /* VN-SHD025 */,
(2237, NULL, N'Chưa có bản quyền') /* PMC008 */,
(2238, NULL, N'Chưa có bản quyền') /* VN-SD003 */,
(2240, NULL, N'Chưa có bản quyền') /* VN-PMC038 */,
(2243, NULL, N'Chưa có bản quyền') /* VN-WK050 */,
(2245, NULL, N'Chưa có bản quyền') /* VN-LTB062 */,
(2246, NULL, N'Chưa có bản quyền') /* VN-LTB063 */,
(2247, N'Có bản quyền', N'Chưa có bản quyền') /* VN-WD006 */,
(2274, NULL, N'Chưa có bản quyền') /* VN-SS051 */,
(2280, NULL, N'Chưa có bản quyền') /* VN-WH061 */,
(2285, NULL, N'Chưa có bản quyền') /* VN-WH003 */,
(2289, NULL, N'Có bản quyền') /* VN-DF029 */,
(2291, NULL, N'Chưa có bản quyền') /* VN-DF023 */,
(2295, NULL, N'Chưa có bản quyền') /* VN-LTB055 */,
(2300, NULL, N'Chưa có bản quyền') /* VN-QC064 */,
(2302, NULL, N'Chưa có bản quyền') /* VN-LTB007 */,
(2304, NULL, N'Chưa có bản quyền') /* VN-LTB033 */,
(2318, NULL, N'Chưa có bản quyền') /* VN-SD056 */,
(2320, NULL, N'Chưa có bản quyền') /* PC-EG */,
(2327, NULL, N'Chưa có bản quyền') /* DF-DLV5.6 */,
(2328, NULL, N'Chưa có bản quyền') /* VN-DF021 */,
(2333, NULL, N'Chưa có bản quyền') /* VN-LD027 */,
(2334, NULL, N'Chưa có bản quyền') /* LTB002 */,
(2336, NULL, N'Chưa có bản quyền') /* VN-LTB064 */,
(2338, NULL, N'Chưa có bản quyền') /* VN-SD094 */,
(2340, NULL, N'Chưa có bản quyền') /* VN-SD061 */,
(2344, NULL, N'Chưa có bản quyền') /* CÂN NHÀ KÍNH */,
(2346, NULL, N'Chưa có bản quyền') /* VN-PMC014 */,
(2351, NULL, N'Chưa có bản quyền') /* VN-QA035 */,
(2353, NULL, N'Chưa có bản quyền') /* VN-LTB051 */,
(2361, NULL, N'Chưa có bản quyền') /* VN-WH065 */,
(2364, NULL, N'Chưa có bản quyền') /* GL-SRV */,
(2365, NULL, N'Chưa có bản quyền') /* YMDC */,
(2367, NULL, N'Chưa có bản quyền') /* VN-WK064 */,
(2368, NULL, N'Chưa có bản quyền') /* ZP-PMC021 */,
(2371, NULL, N'Chưa có bản quyền') /* VN-WK056 */,
(2373, NULL, N'Chưa có bản quyền') /* VN-PMC032 */,
(2374, NULL, N'Chưa có bản quyền') /* VN-LTB059 */,
(2398, NULL, N'Chưa có bản quyền') /* VN-SHD001 */,
(2402, NULL, N'Chưa có bản quyền') /* VN-AC035 */,
(2403, NULL, N'Chưa có bản quyền') /* VN-SHD043 */,
(2404, NULL, N'Chưa có bản quyền') /* VN-AC034 */,
(2405, NULL, N'Chưa có bản quyền') /* VN-QC088 */,
(2468, NULL, N'Chưa có bản quyền') /* VN-ITV031 */,
(2469, NULL, N'Chưa có bản quyền') /* VN-ITV032 */,
(2470, NULL, N'Chưa có bản quyền') /* VN-ITV033 */,
(2471, NULL, N'Chưa có bản quyền') /* VN-ITV034 */,
(2472, NULL, N'Chưa có bản quyền') /* VN-ITV035 */,
(2473, NULL, N'Chưa có bản quyền') /* VN-ITV036 */,
(2474, NULL, N'Chưa có bản quyền') /* VN-ITV037 */,
(2475, NULL, N'Chưa có bản quyền') /* VN-ITV038 */,
(2476, NULL, N'Chưa có bản quyền') /* VN-ITV039 */,
(2477, NULL, N'Chưa có bản quyền') /* VN-ITV040 */,
(2478, NULL, N'Chưa có bản quyền') /* VN-ITV041 */,
(2479, NULL, N'Chưa có bản quyền') /* VN-ITV042 */,
(2480, NULL, N'Chưa có bản quyền') /* VN-ITV043 */,
(2481, NULL, N'Chưa có bản quyền') /* VN-ITV044 */,
(2482, NULL, N'Chưa có bản quyền') /* VN-ITV045 */,
(2483, NULL, N'Chưa có bản quyền') /* VN-ITV046 */,
(2484, NULL, N'Chưa có bản quyền') /* VN-ITV047 */,
(2485, NULL, N'Chưa có bản quyền') /* VN-ITV048 */,
(2486, NULL, N'Chưa có bản quyền') /* VN-ITV049 */,
(2487, NULL, N'Chưa có bản quyền') /* VN-ITV050 */,
(2490, NULL, N'Chưa có bản quyền') /* VN-LTBD006 */,
(2492, NULL, N'Chưa có bản quyền') /* VN-LTBD007 */,
(2494, N'Không xác định', N'Chưa có bản quyền') /* DESKTOP- */,
(2496, NULL, N'Chưa có bản quyền') /* VN-WT001 */;

-- Doi soat TRUOC
SELECT CASE WHEN tb.office_license LIKE N'Có%' OR tb.office_license LIKE N'Office%' THEN N'Có key' ELSE N'Chưa có key' END AS KeyOffice, COUNT(*) AS SoMay
FROM KK_ThietBi tb
WHERE tb.NgayXoa IS NULL AND LTRIM(RTRIM(tb.loai_thiet_bi)) IN (N'Máy tính', N'Laptop') AND ISNULL(LTRIM(RTRIM(tb.ten_may_tinh)), N'') <> N''
GROUP BY CASE WHEN tb.office_license LIKE N'Có%' OR tb.office_license LIKE N'Office%' THEN N'Có key' ELSE N'Chưa có key' END;

UPDATE tb SET tb.office_license = d.gia_tri_moi, tb.ngay_cap_nhat = GETDATE()
FROM KK_ThietBi tb JOIN @doi d ON d.id_thiet_bi = tb.id_thiet_bi
WHERE tb.NgayXoa IS NULL
  AND ISNULL(tb.office_license, N'<NULL>') = ISNULL(d.gia_tri_cu, N'<NULL>');
DECLARE @so INT = @@ROWCOUNT;
PRINT N'Da cap nhat: ' + CAST(@so AS varchar) + N' / 861';

IF @so > 0
    INSERT INTO KK_LichSuThaoTac (HanhDong, DoiTuong, IdDoiTuong, ChiTiet, ThoiGian, NguoiThaoTac)
    VALUES (N'Cập nhật SQL', N'Thiết Bị', 0,
            N'Đồng bộ Key Office theo file Office_license280926.csv: cập nhật ' + CAST(@so AS nvarchar) + N' máy tính/laptop (script kk-key-office-license-20260928.sql).',
            GETDATE(), N'Script SQL');

-- Doi soat SAU: ky vong 279 Co key / 929 Chua co key
SELECT CASE WHEN tb.office_license LIKE N'Có%' OR tb.office_license LIKE N'Office%' THEN N'Có key' ELSE N'Chưa có key' END AS KeyOffice, COUNT(*) AS SoMay
FROM KK_ThietBi tb
WHERE tb.NgayXoa IS NULL AND LTRIM(RTRIM(tb.loai_thiet_bi)) IN (N'Máy tính', N'Laptop') AND ISNULL(LTRIM(RTRIM(tb.ten_may_tinh)), N'') <> N''
GROUP BY CASE WHEN tb.office_license LIKE N'Có%' OR tb.office_license LIKE N'Office%' THEN N'Có key' ELSE N'Chưa có key' END;

-- COMMIT;
-- ROLLBACK;